# Generated by Django 3.2.4 on 2021-06-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfa', '0011_auto_20210530_0622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Keys',
            new_name='UserKey',
        ),
    ]
